version: "3.8"

services:
  portafolio:
    image: nginx:latest
    container_name: portafolio
    volumes:
      - ./portafolio:/usr/share/nginx/html



  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - portafolio
     