
services:
  portafolio:
    build: .
    container_name: portafolio
    restart: always
    labels:
      - "traefik.http.routers.portafolio.rule=host('portafolio.alejandromolar.com')"
    networks:
      - traefik_network
networks:
  traefik_network: 
    external: true
