
services:
  portafolio:
    build: .
    container_name: portafolio
    restart: always
    labels:
      - "traefik.http.routers.portafolio.rule=Host(`alejandromolar.com`)"
      - "traefik.http.services.portafolio.loadbalancer.server.port=80"
    networks:
      traefik_network:
networks:
  traefik_network: 
    name: traefik_net
    driver: bridge
    external: true
